### ISSUE TITLE
Remove min'd editions from the repo

### ISSUE THREAD

**Issue by benschwarz** [benschwarz/metaquery#11]
Perhaps have downloadable editions pushed up to S3… or just don't offer min'd editions at all.

**Comment by CaseyLeask** [comment]
Is there a way to produce min'd assets as part of `bower install`?

**Comment by benschwarz** [comment]
Nope! 

Ref: https://github.com/bower/bower/issues/367

**Comment by CaseyLeask** [comment]
Bugger. For my purposes, I'm going to have to whitelist specific files from each bower_components folder for the build process, which is a pain.
