### ISSUE TITLE
Error "Object expected" in IE8 using metaquery.min.js and modified matchMedia polyfill

### ISSUE THREAD

**Issue by pouipouidesign** [benschwarz/metaquery#12]
Hello,

I can't seem to get this working in IE8, despite calling the modified matchMedia polyfill through Modernizr.
I get a "Object Expected" error on ligne 48 of the non-minified version of metaquery.js, where there is `func.apply( thisArg, args );`.
The same goes for the jQuery version, where the line is then 28 but on the same element (`func.apply( thisArg, args );`).
I hope this is clear...

-- Edit (13/11/03): replacing line 42 of metaquery.js `var args,` by `var args = [],` does shut IE up but alas it doesn't make it work any better? --

Is this a know bug? Or am I doing something wrong?

I'm working on getting this online where you can see it (the client is rather sensitive), in the meantime here is the JS code applied in the document.ready function at the end of my main.js file (after everything else, inc. zepto/jquery and modernizr has loaded): 

``` js
// conditionnaly load and init polyfills
    Modernizr.load([
        // responsive images
        {
          test: !!window.matchMedia,
          nope: './js/vendor/matchMedia.js',
          load: './js/plugins/metaquery.min.js',
        }
    ]);
```

-- Edit (13/11/03): I just realized I hadn't properly pasted my code here, as the test condition was missing its !! at the beginning. Corrected.
I have, however, little to no hope of being able to provide a live example. Still working on it but any meantime help is appreciated. --

Thanks a lot if you have any idea why this is!!

**Comment by pouipouidesign** [comment]
Ok, so, after some more investigating, I managed to make it work:
- I had to load all the js with modernizr, no amount of coaxing worked by just inserting them in `script`tags ;
- I had to remove [respond.js](https://github.com/scottjehl/Respond) who was not playing nice with your plugin.

Although I don't like it as much (not as powerful), [css3-mediaqueries.js](https://code.google.com/p/css3-mediaqueries-js/) brought almost the same functionality — lots of stuff broken that I now have to check — without breaking your plugin.
As for my existing scripts (foundation and a bunch of others), I had to load them all through modernizr too or they just would throw errors: it works but "feels" a bit slower at init/page display, otherwise no other adverse effects seen.

One caveat: it doesn't work on resize, only on pageload, and it keeps throwing that error, so I applied the "hack" I mentioned in the edit of my initial message: "replacing line 42 of metaquery.js `var args,` by `var args = [],`."
It shuts IE up and doesn't seem to have any bad effect?

I hope this can help someone :)

**Comment by benschwarz** [comment]
@pouipouidesign Hey—Thanks for all the info.
What release of metaquery are you using? 

---

FYI, I wouldn't recommend that you use either respond.js or css3-mediaqueries. IE8 just doesn't support MQs, forcing it to do so only makes for a slower user experience.
