### ISSUE TITLE
Future of Metaquery

### ISSUE THREAD

**Issue by CaseyLeask** [benschwarz/metaquery#15]
Stripped out from GChat

Ben Schwarz
so the rewrite
I was working on
basically removes support for ie8
because … there is no media queries

Casey Leask
Is that the `'the-big-rewrite'` branch?

Ben Schwarz
yeah, but I might not have pushed some stuff

Casey Leask
yeah probably, github says it was last updated four months ago

Ben Schwarz
looks like the local changes are just in test stuff
so I dropped ie8 support
which means we can use `domContentLoaded` etc
ahead of here, I was thinking about making the image stuff an optional plugin
which in this unsaved file
you’ll see is about 20 lines long
http://0.germanforblack.com.s3.amazonaws.com/untitled__metaquery_20131030_105817.jpg
(yes, I really wrote that 4 months ago, and never saved it)

Ben Schwarz
It was pseudo code…
I’m sure its fairly close to working anyway
otherwise, I want to make a mini site for it
and get some more adoption there
because its a rad library

Casey Leask
I like it :-)
If you make it into a plugin, I can basically do the same changes I did on the old source to it so you can apply multiple breakpoints.
For me, the retina/width combo is pretty useful.

Ben Schwarz
yeah, I can see that being useful
ideally, the ‘templating’ stuff
used in image

Casey Leask
I'd like to combine them somehow, so mobile+retina = small-tablet etc, but I'm not sure that first version stuff

Ben Schwarz
should work on any element with a `data-attr-template=“/images/[breakpoint].jpg” data-att=“src”`
and perhaps even pull other metadata, like the media query…
not sure that’d be useful
but basically, I thought
`<meta name=“breakpoint” media=“@query here” data-var-name=“value”>`
that `data-var-name` could be also shuffled through as meta data
… with me>
… thats all I have, anyway

Casey Leask
So switching the attr `'content'` for `'data-var-name'`?

Ben Schwarz
hum, more directly
to have variables
`<img src=“small.jpg” data-mq-template=“[varname].jpg”>`
… or something like that anyway
its kind of hard to believe I wrote the initial stuff 4 months ago

Casey Leask
ah, I think I get you.
Could it be used like this?
`<img src="small.jpg" data-mq-template="[width]-[dpi].jpg">`

Ben Schwarz
yeah
thats kind of where I was going
wouldn’t increase the code much
but it would mean you could use image processing server side etc
or… whatever

Casey Leask
yeah.

Ben Schwarz
so thats where I was hoping to go

Casey Leask
fair enough! I've made a gist of that so I can take a look at it later. https://gist.github.com/CaseyLeask/7225174

Ben Schwarz
Glen really likes putting mq into the head of the doc `<script>the code here, literally</script>`
after the meta tags
because its so small and fast that way
I haven’t messed with that much
but you could also use `<script async src=“pth/to/mq”>`

Casey Leask
yeah, setting it async in the head was what i was going to do
since the project I'm working on is in a CMS, the plan is to use the image stuff for CMS images and use the breakpoint classnames for the images defined in the css

Ben Schwarz
sounds fair

Casey Leask
that way I can sidestep the initial load of the mobile image in cases where I don't need it

Ben Schwarz
also, you can use `<img>` (without a src)
or even use breakpoint matchers to ajax in more content
perhaps

Casey Leask
`<img data-mq-src="[breakpoint].jpg">`
`<noscript><img src="mobile"></noscript>`

**Comment by benschwarz** [comment]
ping @geelen

**Comment by CaseyLeask** [comment]
I've forked the gist @geelen made in his blog post at https://gist.github.com/CaseyLeask/8930432 with the proposed changes. Let me know if I'm wrong.

**Comment by benschwarz** [comment]
Thanks @CaseyLeask, I left some comments on your gist.
I'd like to think about the metadata variables that we could expose (the mediaquery, the name of the breakpoint?) and I guess we need to consider that multiple media queries can match… so what happens to the variables?
