### ISSUE TITLE
Not working with Browserify - Needs to be re-uglified

### ISSUE THREAD

**Issue by fubhy** [benschwarz/metaquery#26]
Thanks for sharing this and thanks for making it work with Browserify.

However, when using Browserify with browserify-shim and debowerify (installing metaquery through bower and using it in Browserify) it's currently broken because the shim looks into .bower.json which targets the already uglified metaquery.min.js which has not been re-uglified since the latest changes that make this repository work with Browserify.

**Comment by fubhy** [comment]
Sorry... My fault. You actually updated the .min.js but the Bower reference is behind it seems.

**Comment by fubhy** [comment]
To circumvent this problem use this for now: bower install metaquery#master --save

**Comment by benschwarz** [comment]
Hmm. So I should tag a new version?

**Comment by geelen** [comment]
You can force push a new tag if you need to. It's the worst bit about
Bower, but in this case it might be most appropriate?

**Comment by benschwarz** [comment]
Tags are free! I created a new one :-)

`1.2.4`

Enjoy, and thanks for the report! :sailboat:
