### ISSUE TITLE
Unprefix min-device-pixel-ratio

### ISSUE THREAD

**Issue by nimbupani** [benschwarz/metaquery#4]
This needs to be done within the script to add prefixes. device pixel ratio applies not just for Webkit but for other rendering engines as well.

**Comment by benschwarz** [comment]
@miketaylr suggested I change the readme in reference to: 
http://www.w3.org/blog/CSS/2012/06/14/unprefix-webkit-device-pixel-ratio

Any other hints to the unprefixing in practice?

**Comment by benschwarz** [comment]
https://developer.mozilla.org/en-US/docs/CSS/Media_queries states a bunch of media queries I've never heard of, including the unprefixable: `min--moz-device-pixel-ration` for Firefox before version 16!

This requires more R&D in respects to mobile editions of browsers.
