### ISSUE TITLE
updateClasses mashes preexistent classnames together

### ISSUE THREAD

**Issue by jddh** [benschwarz/metaquery#5]
I'm using your fine script in a situation where the html element loads with another classname, inserted elsewhere programmatically. When metaquery updates its classes, it mistakenly adds its classes to the preexistent class as well. For example:

```
<html class="js">
```

becomes

```
<html class="js breakpoint-desktop"> 
```

but then

```
<html class="jsbreakpoint-phone breakpoint-phone"> 
```

etc

**Comment by benschwarz** [comment]
@jddh, that sucks—I'll come up with a fix soon. 
In the meantime, I'd suggest that you use the jquery version. It won't feature the same bug. 

ps.  @cowboy warned me about using these methods without unit tests for them, and here we are :-)
